=== SAMARITAN-INTERNATIONAL-EU/AdaptDB/API/version 1/findStreetsByName_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "List of streets",
  "type": "array",
    "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
        "zipcode": {
        "type": "string"
      },
        "city": {
        "type": "string"
      }
    }, "required": [
      "id",
      "name",
      "zipcode",
      "city"
    ]
}
}

=== SAMARITAN-INTERNATIONAL-EU/AdaptDB/API/version 1/findStreetsByName_example.json
[
  {
    "id": 64,
    "name": "Angel Via",
    "zipcode": "44284-6105",
    "city": "Lake Kaitlynfurt"
  },
  {
    "id": 62,
    "name": "Ashleigh Via",
    "zipcode": "64222-0182",
    "city": "West Elnaland"
  },
  {
    "id": 12,
    "name": "Moen Via",
    "zipcode": "23939",
    "city": "Eichmannfurt"
  }
]
