=== SAMARITAN-INTERNATIONAL-EU/AdaptDB/API/version 1/getDataSources_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Array of all zipcodes in the database",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "name_short": {
        "type": "string"
      },
      "is_official": {
        "type": "boolean"
      },
      "default_for_automatic_update_for_clearly_identified_addresses": {
        "type": "boolean"
      },
      "default_for_detect_missing_persons": {
        "type": "boolean"
      },
      "default_for_enable_geocoding": {
        "type": "boolean"
      }
    },
    "required": [
      "id",
      "name",
      "name_short",
      "is_official",
      "default_for_automatic_update_for_clearly_identified_addresses",
      "default_for_detect_missing_persons",
      "default_for_enable_geocoding"
    ]
  }
}

=== SAMARITAN-INTERNATIONAL-EU/AdaptDB/API/version 1/getDataSources_example.json
[
  {
    "id": 1,
    "name": "Backend",
    "name_short": "BE",
    "is_official": false,
    "default_for_automatic_update_for_clearly_identified_addresses": true,
    "default_for_detect_missing_persons": false,
    "default_for_enable_geocoding": true
  },
  {
    "id": 2,
    "name": "Registration office",
    "name_short": "RO",
    "is_official": true,
    "default_for_automatic_update_for_clearly_identified_addresses": true,
    "default_for_detect_missing_persons": true,
    "default_for_enable_geocoding": true
  },
  {
    "id": 3,
    "name": "Meals on Wheels",
    "name_short": "MW",
    "is_official": false,
    "default_for_automatic_update_for_clearly_identified_addresses": false,
    "default_for_detect_missing_persons": false,
    "default_for_enable_geocoding": true
  }
]
